### ISSUE TITLE
[request] tags for version releases

### ISSUE THREAD

**Issue by samuela** [pirl-unc/mhcgnomes#20]
I'm working on packaging mhcgnomes for [nixpkgs](https://github.com/NixOS/nixpkgs). To facilitate downstream packaging it is helpful to have version tags. For example, looking through the commit history it appears that https://github.com/pirl-unc/mhcgnomes/commit/c7e779b60e35a031f6e0f0ea6ae70e8a8e7671c6 is the 1.8.6 version commit.

Not essential, but would it be possible to get version tags? Thanks!

**Comment by iskandr** [comment]
Just added it to the deploy script, next release (once tests are working with GH Actions CI) will have tags.
